#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.
export XDG_CURRENT_DESKTOP=KDE
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

# Change your keymap:
xmodmap "/home/jinzhouz/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# Start DBUS session bus:
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
   eval $(dbus-launch --sh-syntax --exit-with-session)
fi

# set wmname to LG3D to solve JAVA problem
which wmname &>/dev/null
if [ $? == 0 ]; then
    wmname "LG3D"
fi

# set keyboard repeat speed
if hash xset 2>/dev/null; then
    xset r rate 200 40
fi

fcitx &

# xscreensaver
if hash xscreensaver 2> /dev/null; then
    xscreensaver -no-splash &
elif hash gnome-screensaver 2> /dev/null; then
    gnome-screensaver &
fi

# echo "Starting auto-sync tools"
sleep 60 && dropbox start &

if hash skippy-xd 2> /dev/null; then
    skippy-xd --start-daemon &
fi

if hash teamviewer 2> /dev/null; then
    sleep 60 && teamviewer &
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

if hash dunst 2> /dev/null; then
    dunst &
fi

#exec fluxbox
# or if you want to keep a log:
exec fluxbox -log "/home/jinzhouz/.fluxbox/log"
